const QrCode = () => {
    return (
        <>
        <div className="container">
            <h1 className="header">QR CODE GENERATOR</h1>
            <div className="Qr-container">
                <img className="Qr-img" src="img.jpg" alt="" />
                <label htmlFor="dataInput" className="input-label">Data For Qr Code : </label>
                <input placeholder="Enter Qr-data" type="text" id="dataInput" />
                <label htmlFor="sizeInput" className="input-label">Image Size (e.g.,150):</label>
                <input placeholder="Enter size of  Qr-data" type="text" id="sizeInput" />
                <div className="QR-Buttons">
                <button className="Generate-btn">Generate QR Code</button>
                <button className="Download-btn">Download QR Code</button>
                </div>
            </div>
            <h2 className="footer"> Generated By <span> HariPrasath</span> </h2>
        </div>
        </>
    );
}

export default QrCode;